DROP TABLE IF EXISTS PART;
CREATE TABLE PART (

    P_PARTKEY       BIGINT PRIMARY KEY,
    P_NAME          VARCHAR(55),
    P_MFGR          CHAR(25),
    P_BRAND         CHAR(10),
    P_TYPE          VARCHAR(25),
    P_SIZE          INTEGER,
    P_CONTAINER     CHAR(10),
    P_RETAILPRICE   DECIMAL,
    P_COMMENT       VARCHAR(23),
    P_DUMMY         CHAR(1)
);

DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER (
    S_SUPPKEY       BIGINT PRIMARY KEY,
    S_NAME          CHAR(25),
    S_ADDRESS       VARCHAR(40),
    S_NATIONKEY     BIGINT NOT NULL, -- references N_NATIONKEY
    S_PHONE         CHAR(15),
    S_ACCTBAL       DECIMAL,
    S_COMMENT       VARCHAR(101),
    S_DUMMY         CHAR(1)
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    C_CUSTKEY       BIGINT PRIMARY KEY,
    C_NAME          VARCHAR(25),
    C_ADDRESS       VARCHAR(40),
    C_NATIONKEY     BIGINT NOT NULL, -- references N_NATIONKEY
    C_PHONE         CHAR(15),
    C_ACCTBAL       DECIMAL,
    C_MKTSEGMENT    CHAR(10),
    C_COMMENT       VARCHAR(117),
    C_DUMMY         CHAR(1)
);

DROP TABLE IF EXISTS ORDERORDER;
CREATE TABLE ORDERORDER (
    O_ORDERKEY      BIGINT PRIMARY KEY,
    O_CUSTKEY       BIGINT NOT NULL, -- references C_CUSTKEY
    O_ORDERSTATUS   CHAR(1),
    O_TOTALPRICE    DECIMAL,
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK         CHAR(15),
    O_SHIPPRIORITY  INTEGER,
    O_COMMENT       VARCHAR(79),
    O_DUMMY         CHAR(1)
);

DROP TABLE IF EXISTS LINEITEM ;
CREATE TABLE LINEITEM (
    L_ORDERKEY      BIGINT NOT NULL, -- references O_ORDERKEY
    L_PARTKEY       BIGINT NOT NULL, -- references P_PARTKEY (compound fk to PARTSUPP)
    L_SUPPKEY       BIGINT NOT NULL, -- references S_SUPPKEY (compound fk to PARTSUPP)
    L_LINENUMBER    INTEGER,
    L_QUANTITY      DECIMAL,
    L_EXTENDEDPRICE DECIMAL,
    L_DISCOUNT      DECIMAL,
    L_TAX           DECIMAL,
    L_RETURNFLAG    CHAR(1),
    L_LINESTATUS    CHAR(1),
    L_SHIPDATE      DATE,
    L_COMMITDATE    DATE,
    L_RECEIPTDATE   DATE,
    L_SHIPINSTRUCT  CHAR(25),
    L_SHIPMODE      CHAR(10),
    L_COMMENT       VARCHAR(44),
    L_DUMMY         CHAR(1),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

DROP TABLE IF EXISTS NATION;
CREATE TABLE NATION (
    N_NATIONKEY     BIGINT PRIMARY KEY,
    N_NAME          CHAR(25),
    N_REGIONKEY     BIGINT NOT NULL,  -- references R_REGIONKEY
    N_COMMENT       VARCHAR(152),
    N_DUMMY         CHAR(1)
);

DROP TABLE IF EXISTS REGION;
CREATE TABLE REGION (
    R_REGIONKEY BIGINT PRIMARY KEY,
    R_NAME      CHAR(25),
    R_COMMENT   VARCHAR(152),
    R_DUMMY     CHAR(1)
);

COPY PART FROM '/home/ec2-user/skewed/part.tbl' WITH DELIMITER '|';
COPY SUPPLIER FROM '/home/ec2-user/skewed/supplier.tbl' WITH DELIMITER '|';
COPY CUSTOMER FROM '/home/ec2-user/skewed/customer.tbl' WITH DELIMITER '|';
COPY ORDERORDER FROM '/home/ec2-user/skewed/order.tbl' WITH DELIMITER '|';
COPY LINEITEM FROM '/home/ec2-user/skewed/lineitem.tbl' WITH DELIMITER '|';
COPY NATION FROM '/home/ec2-user/skewed/nation.tbl' WITH DELIMITER '|';
COPY REGION FROM '/home/ec2-user/skewed/region.tbl' WITH DELIMITER '|';

